name: pet_shop
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  badges: ^3.1.2
  introduction_screen: ^3.1.14
  sms_otp_auto_verify: ^2.1.0
  animated_bottom_navigation_bar: ^1.3.3
  fan_carousel_image_slider: ^1.0.1
  flutter_rating_bar: ^4.0.1
  intl_phone_field: ^3.2.0
  sms_autofill: ^2.4.0
  shared_preferences: ^2.2.3

  #Loading
  shimmer: ^3.0.0

  #Camera
  image_cropper: ^7.0.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  camera: ^0.11.0+1
  oktoast: ^3.4.0
  path: ^1.9.0
  path_provider: ^2.1.3

  #Api
  http:
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.9
  flutter_secure_storage: ^9.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/_project/Account/
    - assets/images/_project/Home/
    - assets/images/_project/Icons/
    - assets/images/_project/Logo/
    - assets/images/_project/Logo/social/
    - assets/images/_project/On_Boarding/
    - assets/images/_project/Payment/
    - assets/images/_project/Plash_Screen/
    - assets/images/_project/Products/
    
